name: "Build NS with inline-patch (emacs-26)"
on:
  pull_request:
  schedule:
  - cron: '0 6 * * *'

jobs:
  build-26:
    runs-on: macos-latest
    timeout-minutes: 60
    steps:
    - uses: actions/checkout@v2
    - name: Setup to build
      run: sh build/setup.sh
    - name: Build emacs-26.3 with inline patch
      run: sh build/emacs-26.3.sh -d ${{ github.workspace }}
    - name: Verification
      run: ${{ github.workspace }}/emacs_ns/emacs-26.3/nextstep/Emacs.app/Contents/MacOS/Emacs --batch --eval="(unless (fboundp 'mac-input-method-mode) (error \"The inline-patch is NOT integrated\"))"
