name: "Build NS with inline-patch (HEAD)"
on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
  - cron: '0 5 * * *'

jobs:
  build-head:
    runs-on: macos-latest
    timeout-minutes: 90
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Setup to build
      run: sh build/setup.sh
    - name: Build HEAD with inline patch
      run: sh build/emacs-head.sh -d ${{ github.workspace }} -n
    - name: Verification
      run: ${{ github.workspace }}/emacs/nextstep/Emacs.app/Contents/MacOS/Emacs --batch --eval="(unless (fboundp 'mac-input-method-mode) (error \"The inline-patch is NOT integrated\"))"
