name: "Build NS with inline-patch (HEAD)"
on:
  push:
  pull_request:
  schedule:
  - cron: '0 7 * * *'

jobs:
  build-head:
    runs-on: macos-latest
    timeout-minutes: 60
    steps:
    - uses: actions/checkout@v2
    - name: Setup to build
      run: sh build/setup.sh
    - name: Build emacs-28 with inline patch
      run: sh build/emacs-head.sh -d ${{ github.workspace }}
    - name: Verification
      run: ${{ github.workspace }}/emacs/nextstep/Emacs.app/Contents/MacOS/Emacs --batch --eval="(unless (fboundp 'mac-input-method-mode) (error \"The inline-patch is NOT integrated\"))"
