name: "Build NS with inline-patch"
on:
  push:
  pull_request:
  schedule:
  - cron: '0 6 * * *'

jobs:
  build-head:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup to build
      run: sh build/setup.sh
    - name: Build emacs-28 with inline patch
      run: sh build/emacs-head.sh -d ${{ github.workspace }}
    - name: Verification
      run: ${{ github.workspace }}/emacs/nextstep/Emacs.app/Contents/MacOS/Emacs --batch --eval="(unless (fboundp 'mac-input-method-mode) (error \"The inline-patch is NOT integrated\"))"
  build-27_0:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup to build
      run: sh build/setup.sh
    - name: Build emacs-27 with inline patch
      run: sh build/emacs-27.1.sh -d ${{ github.workspace }}
    - name: Verification
      run: ${{ github.workspace }}/emacs/nextstep/Emacs.app/Contents/MacOS/Emacs --batch --eval="(unless (fboundp 'mac-input-method-mode) (error \"The inline-patch is NOT integrated\"))"
  build-26_3:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup to build
      run: sh build/setup.sh
    - name: Build emacs-26.3 with inline patch
      run: sh build/emacs-26.3.sh -d ${{ github.workspace }}
    - name: Verification
      run: ${{ github.workspace }}/emacs_ns/emacs-26.3/nextstep/Emacs.app/Contents/MacOS/Emacs --batch --eval="(unless (fboundp 'mac-input-method-mode) (error \"The inline-patch is NOT integrated\"))"
