name: "Build NS with inline-patch (emacs-29)"
on:
  pull_request:
  workflow_dispatch:
  schedule:
  - cron: '0 8 * * *'

jobs:
  build-29:
    runs-on: macos-latest
    timeout-minutes: 61
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Setup to build
      run: sh build/setup.sh
    - name: Build emacs-29 with inline patch
      run: sh build/emacs-head.sh -b emacs-29 -d ${{ github.workspace }} -p inline
    - name: Verification
      run: ${{ github.workspace }}/emacs/nextstep/Emacs.app/Contents/MacOS/Emacs --batch --eval="(unless (fboundp 'mac-input-method-mode) (error \"The inline-patch is NOT integrated\"))"
